### ISSUE TITLE
choosing MoveJ yields MoveL

### ISSUE THREAD

**Issue by bhomaidan1990** [abedGNU/vscode-abb-rapid#2]
When I try to type `Move..` I get two options: `movej`, and `movel`, but it turns to be that choosing any of them yeilds `MoveL`: 
```
MoveL robtarget, speed,fine,tool;
MoveL topoint, speed,zone,tool;
```
can you please tell me how to get MoveJ? thanks in advance.

**Comment by jereytucker** [comment]
# #commit

**Comment by jereytucker** [comment]
# #commit
